app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_bank_account_details.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_claim.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_claimant_details_as_importer_company.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_claimant_details_as_individual.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_commodities_details.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_declarant_eori_number.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_declaration_details.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_importer_eori_number.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_movement_reference_number.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_basis_for_claim.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_duties.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_reason_and_basis_for_claim.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_who_is_making_the_claim.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/error_summary.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/supportingevidence/choose_document_type.scala.html
That turned into a rabbit hole quickly - I've tested the Entry number journey end-to-end and get most summary error links working. Only page I couldn't do was the `enter claim` page.
=> CDS-521 - Fixing error summary links

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_duplicate_movement_reference_number.scala.html, conf/messages
Because this page largely uses the same content as `Enter MRN` I've hard-coded the title key specific to this page rather than duplicating content in the messages file.
=> CDSR-517 - Added heading & help text for duplicate MRN page

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Router.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/SessionDataExtractor.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterMovementReferenceNumberController.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/SessionDataExtractorSpec.scala
Changes,
1) Instead of having two getRoutes methods, consolidate on one. Forces MRN controller to get number of claims out of session, but that's a good thing IMO.
2) Collapse nested if/else and multiple pattern matchs into single pattern match. 
End result
Makes it impossible to get onto later pages if you don't have the right thing in your session.
=> some suggestions

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_commodities_details.scala.html, conf/messages
In the messages file enter-commodities-details.label= is left blank, this is because this label is intrinsic to checkPageIsDisplayed() in the tests.  The tests fail if this message key is removed.
=> CDSR-689-1: remove label and help text; change error message

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/fileupload/SupportingEvidenceController.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/fileupload/SupportingEvidenceControllerSpec.scala
Ensure that the user can continue to the CYA page if they have entered the maximum number of document.
=> CDSR-1056: Ensure that the user can continue to the CYA page

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterSingleClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/answers/package.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_single_claim_summary.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/utils/ClaimSummaryHelper.scala, conf/messages, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterSingleClaimControllerSpec.scala
This PR is a quick-fix for three issues:
- when changing the existing answer wrong amount was pre-populated, should be the corrected amount, not the reimbursed
- the look of a summary page was different to the prototype, new UI needs MRN
- after changing the amount and getting back to the summary the order of duties was different
=> [CDSR-1247][AO] fix single claim input and summary page

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/ClaimConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/RejectedGoodsSingleClaimConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/Retries.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckEoriDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ChooseClaimTypeController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/ClaimService.scala, conf/application.conf, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/ClaimConnectorSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/HttpSupport.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/RejectedGoodsSingleClaimConnectorSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckEoriDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/ClaimServiceSpec.scala
This PR adds new connector to the backend endpoint `/claims/rejected-goods-single`.
=> [CDSR-1254][AO] add connector to submit rejected goods single claim

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyControllerComponents.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/FeatureSwitchProtectedAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/SessionDataAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckContactDetailsMrnController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckEoriDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ChooseClaimTypeController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ClaimNorthernIrelandController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/DummyExampleController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/RejectedGoodsSingleJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/Feature.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchService.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/testonly/controllers/FeatureSwitchController.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckContactDetailsMrnControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckEoriDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckMovementReferenceNumbersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ChooseClaimTypeControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ClaimNorthernIrelandControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterAssociatedMrnControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterMovementReferenceNumberControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/SelectBasisForClaimControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/SelectTypeOfClaimControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchServiceSpec.scala
This PR amends `JourneyBaseController` with new features:
- current user retrieval
- feature switch check if needed
- automatic redirect to CYA when journey complete after modifications
The new `JourneyControllerComponents` is now the main required dependency on every journey controller.
Additionally bizarre feature switch model and service has been simplified.
=> make base journey controller to check feature switch and redirect to CYA if journey complete

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/BasisOfRejectedGoodsClaim.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/ClaimantInformation.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/ContactInformation.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/answers/ClaimantType.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/ConsigneeDetails.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/ConsigneeOrDeclarantDetails.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/DisplayDeclaration.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/utils/EnumerationFormat.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyFormatSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneySpec.scala
This PR alters the `RejectedGoodsSingleJourney` by:
- adding new enum `ClaimantType` and getClaimantType method
- adding new `ClaimantInformation` case class and **claimantInformation** field on the `Output` model
- simplified serialization format for the new type of enums
The **claimantInformation** field represents directly the expected content of TPI05:EORIDetails/agentEORIDetails field. 
The content of  TPI05:EORIDetails/ImporterEORIDetails should be populated based on ACC14:consigneeDetails.
=> [CDSR-1256][AO] add ClaimantType and ClaimantInformation to the RGSJ Output

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckDeclarationDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckDuplicateDeclarationDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckScheduledClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckYourAnswersAndSubmitController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_bank_account_details.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_declaration_details.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_scheduled_claim_summary.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_your_answers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/AnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/BankAccountDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/BasisOfClaimSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/CdsClaimantDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ClaimTypeSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ClaimedReimbursementsAnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/CommodityDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/DisplayDeclarationSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/DutyAndTaxCodeReimbursementSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/MovementReferenceNumberSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/MovementReferenceNumbersSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/MultipleClaimsAnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/NorthernIrelandAnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ReimbursementMethodAnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ScheduledDocumentSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/SupportingEvidenceSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/TaxCodeReimbursementSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/package.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/utils/ClaimantDetailsHelper.scala
This PR includes a lot of refactoring to allow for removing ReimbursementRoutes from the check_declaration_details template.
Refactoring includes: 
- Removing ReimbursementRoutes from check_your_answers template and controller
- Removing ReimbursementRoutes from summary helpers
- Including JourneyBindable and subKey in summary helpers
- Including JourneyBindable and subKey as an implicit for render method
- Changing any subsequent templates that use the summary/render method (mini journey summary pages)
=> CDSR-328: refactor check_declaration_details template and controller

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterDeclarantEoriNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterImporterEoriNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckClaimantDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/contactdetails/Name.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/EstablishmentAddress.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ClaimantDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/RejectedGoodsAnswerSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/package.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/rejectedgoodssingle/check_claimant_details.scala.html, conf/messages, conf/rejected_goods_single.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterDeclarantEoriNumberControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterMultipleClaimsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckClaimantDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyTestData.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/generators/IdGen.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/generators/RetrievedUserTypeGen.scala
The view summaries are tightly couple with the journey bindable object so we have created a new version of it that is not connected to it.
We have created a new version of the twirl template that does takes in the details we wish to display, and the controller determines what these details should be. As we are under pressure to get the C&1179 pages completed we have not updated the C285 pages to use this updated twirl template. The plan is to create some tech-debt tickets on the backlog to make sure that we go back and do this work.
=> CDSR-1262: Check claimant details

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/RejectedGoodsMultipleJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/RejectedGoodsSingleJourneyBaseController.scala
This PR adds additional check before forwarding to CYA, it is now possible only after user has already seen CYA and journey is complete and action does not opt-out. It solves the problem with optional questions which user should be able to answer at least once. This should not be the concern of particular actions.
=> improve CYA forwarding logic

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/StartController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionWithRetrievedData.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/RetrievedUserType.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/StartControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionWithRetrievedDataSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/generators/RetrievedUserTypeGen.scala
This PR fixes contact details retrieval for Organisation-type users, currently they cannot pass the claimant-details page.
=> [AO] retrieve email when user is an Organisation and fix computeContactDetails function

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckBankDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckClaimantDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/AccountNumber.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/BankAccountDetails.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/SortCode.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/DisplayDeclaration.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/BankAccountDetailsSummary.scala, conf/messages, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/ControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/CheckYourSingleJourneyAnswersSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/CheckYourAnswersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckBankDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckYourAnswersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/ChooseInspectionAddressTypeControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyGenerators.scala
This PR:
- fixes missing BankAccountDetails preventing CYA page when the user confirms bank account details existing in ACC14
- fixes rendering of bank account details in summaries
- renames getBankAccountDetails to computeBankAccountDetails
- adds more tests to CheckBankDetailsControllerSpec
- fixes flaky ChooseInspectionAddressTypeControllerSpec
=> [CDSR-1478][AO] always store BankAccountDetails in the journey, show account details masked

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/RejectedGoodsMultipleJourneyRouter.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/CheckYourAnswersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckYourAnswersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyTestData.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourneySpec.scala
This PR fixes few bugs in multiple and single journey data model:
- it must be not possible to remove second MRN from multiple journey if only two MRNs left,
- it must be not possible to complete multiple journey with less then two MRNs,
- checkYourAnswersChangeMode flag can be only set if journey is complete,
- should generate test journeys with no supporting evidence
=> CDSR-1332-fix-second-mrn-removal

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/config/UploadDocumentsConfig.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/UploadDocumentsConnectorSpec.scala
This PR accompanies the change made in https://github.com/hmrc/upload-documents-frontend/pull/14
=> change to use new internal route prefix in upload-documents-frontend

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/EnterMovementReferenceNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/DisplayDeclaration.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyTestData.scala
Lead MRN EORIs should match EORIs from ACC14 for the subsequent MRNs. 
The scenario is already handled [here](https://github.com/hmrc/cds-reimbursement-claim-frontend/blob/5c12062838b257aebd7a98a2d94413939bfe9d82/app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala#L227) so this fix is just to redirect to `/check-movement-reference-numbers` instead of `/enter-importer-eori` for the non-lead MRNs
=> CDSR-1349: Bug fix for subsequent movement in multiple MRN journey

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterImporterEoriNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterMovementReferenceNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/RejectedGoodsSingleJourneyRouter.scala, conf/rejected_goods_scheduled.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterImporterEoriNumberControllerSpec.scala
As a trader on a C&E1179 Scheduled journey
I want to enter the importer eori, if I fail the initial eori check
So that I get a second chance to validate my EORIs against the EORIs brought back by ACC14.
=> CDSR-1344 C&E1179 Scheduled | /enter-importer-eori

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/BankAccountReputationConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/CDSReimbursementClaimConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/ConnectorError.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/Error.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/BankAccountReputationService.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/ClaimService.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/utils/Logging.scala, conf/application.conf, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/BankAccountReputationConnectorSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/CDSReimbursementClaimConnectorSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/RejectedGoodsScheduledClaimConnectorSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/MockBankAccountReputationService.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/BankAccountControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/generators/BankAccountReputationGen.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/ClaimServiceSpec.scala
CDSR-1604 add MockBankAccountReputationService
CDSR-1604 fix updated bank account number issue with failing BankAccountControllerSpec
CDSR-1604 eod work on BankAccountReputationConnectorSpec BankAccountReputationService
CDSR-1604 add retries to BankAccountReputationConnector
CDSR-1604 generated business request 200 test passing
CDSR-1604 generated personal request 200 test passing
CDSR-1604 error when 5xx response status in the third attempt passing
CDSR-1604 all 5xx response tests passing
CDSR-1604 200 response witjh invalid payloads passing
CDSR-1604 201 tests passing
CDSR-1604 404 tests passing, tidy up
CDSR-1604 formatting
CDSR-1604 add ConnectorError and merge BankAccountReputationConnector
CDSR-1604 merge BankAccountReputationService
CDSR-1604 merge claims/BankAccountController …
=> CDSR-1604 creating seperate BARS service, connector and model rules

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Router.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterAdditionalDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/CheckMovementReferenceNumbersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterAssociatedMrnController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterMultipleClaimsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/SelectMultipleDutiesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_movement_reference_numbers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_your_answers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_associated_mrn.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_multiple_claims.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_multiple_duties.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/MovementReferenceNumbersSummary.scala, conf/claims.routes, conf/overpayments_multiple.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/EnterAdditionalDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/CheckMovementReferenceNumbersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterAssociatedMrnControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterMultipleClaimsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/SelectMultipleDutiesControllerSpec.scala
This PR moves the following endpoints:
- /multiple/enter-movement-reference-number/:index
- /multiple/change-movement-reference-number/:index
- /multiple/select-duties/:index
- /multiple/select-duties/:index/:taxCode
- /multiple/check-claim
=> [CDSR-1724] move multiple-only controllers into the overpaymentsmultiple package

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/SelectDutyTypesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/CheckScheduledClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/EnterScheduledClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/SelectDutyCodesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_scheduled_claim_summary.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_your_answers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/TaxCodeReimbursementSummary.scala, conf/claims.routes, conf/overpayments_scheduled.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/SelectDutyTypesControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/CheckScheduledClaimControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/EnterScheduledClaimControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/SelectDutyCodesControllerSpec.scala
This PR affects the following endpoints:
- /scheduled/select-duties/start
- /scheduled/select-duties/:DutyType
- /scheduled/select-duties/reimbursement-claim/start
- /scheduled/select-duties/:dutyType/:taxCode
- /scheduled/check-claim
=> [CDSR-1725] move C285 Scheduled controllers into the overpaymentsscheduled package

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Router.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/UploadMrnListController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_your_answers.scala.html, conf/claims.routes, conf/overpayments_scheduled.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/RouterSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/UploadMrnListControllerSpec.scala
This PR moves controllers serving the following endpoints:
- /scheduled/scheduled-document-upload/choose-files 
- /scheduled/scheduled-document-upload/continue
=> [CDSR-1729] move /scheduled/scheduled-document-upload/choose-files and /scheduled/scheduled-document-upload/continue

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/CDSReimbursementClaimConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/ConnectorError.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterAdditionalDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/EnterSingleClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/SelectDutiesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_single_claim_summary.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/check_your_answers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/enter_single_claim.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/claims/select_duties.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/utils/ClaimSummaryHelper.scala, conf/claims.routes, conf/overpayments_single.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/EnterAdditionalDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/EnterSingleClaimControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/SelectDutiesControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/SelectTaxCodesControllerSpec.scala
This PR moves the controllers representing the following endpoints:
- /select-duties
- /single/start-claim
- /single/enter-claim/:id
- /single/check-claim
=> [CDSR-1726] move single only controller into the overpaymentssingle package

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Forms.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/common/ChooseClaimTypeController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/mixins/WorkInProgressMixin.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/CheckYourAnswersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterMovementReferenceNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SecuritiesJourneyRouter.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SecurityPickerController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SelectDutiesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyValidationErrors.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/DisplayDeclaration.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/utils/DateUtils.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/EvidenceDocumentsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/SecuritiesCdsDisplayDeclarationSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/SecuritiesReclaimDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/SecuritiesSelectionSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/securities/check_your_answers.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/securities/choose_reason_for_security.scala.html, conf/messages, conf/securities.routes, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/claims/ChooseClaimTypeControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/CheckYourAnswersControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/ChooseReasonForSecurityControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterMovementReferenceNumberControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyTestData.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneyFormatSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneyTestData.scala
This PR adds CYA page for Securities journey. Sample session state for securities can be generated by running `SecuritiesJourneyFormatSpec`.  External display  declaration details are not yet included as it depends on CDSR-1782.
=> [CDSR-1792] display check-your-answers page for securities

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterDeclarantEoriNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterDeclarantEoriNumberController.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterDeclarantEoriNumberControllerSpec.scala
Previous change was made in the wrong EnterDeclarantEoriNumberController. This reverts and puts the fix in the right place.
=> CDSR-1546 fix

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/mixins/WorkInProgressMixin.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/CheckYourAnswersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/RejectedGoodsMultipleJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/CheckYourAnswersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/RejectedGoodsScheduledJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/CheckYourAnswersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/RejectedGoodsSingleJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/CheckDeclarationDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/CheckYourAnswersController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterMovementReferenceNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SecuritiesJourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SecuritiesJourneyRouter.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/Claim.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsScheduledJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsSingleJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourney.scala, project/AppDependencies.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/CheckDeclarationDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SelectSecuritiesControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/RejectedGoodsMultipleJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneySpec.scala
Thiis PR apart from implementing CDSR-1550 also upgrades validator library and introduces optional action precondition checks support in the base journey controller. We will try to introduce action precondition checks across all Securities' controllers and later retrospectively in the RejectedGoods.
=> [CDSR-1550] Securities | US1:AC4 /check-declaration-details

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Forms.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/ConfirmFullRepaymentController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterClaimController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SelectDutiesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/SelectSecuritiesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourney.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/ConfirmFullRepayment.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/securities/confirm_full_repayment.scala.html, conf/messages, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/ConfirmFullRepaymentControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/JourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneyGenerators.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneySpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourneyTestData.scala
CDSR-1776 add ConfirmFullRepaymentControllerSpec
CDSR-1776 formatting
CDSR-1776 implement show method in controller
CDSR-1776 basic page load validation passing with complete journey
CDSR-1776 implement minimal submit method in controller
CDSR-1776 redirect to error page if called with an invalid security id test passing
CDSR-1776 AC5 passing, AC2 wip - need to have test data with security deposit id having a valid security reclaim set
=> CDSR-1776 add html, summary and draft controller

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/Forms.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/mixins/EnterBankAccountDetailsMixin.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/BankAccountController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterBankAccountDetailsController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/utils/Syntax.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/common/enter_bank_account_details.scala.html, conf/messages, conf/messages.cy, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/BankAccountControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/BankAccountControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/BankAccountControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsmultiple/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodsscheduled/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterBankAccountDetailsControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterBankAccountDetailsControllerSpec.scala
…tDetailsController, refactor common code and template
CDSR-1560 refactor common code
CDSR-1560 AC1 passing
CDSR-1560 factor out common code into EnterBankDetailsMixin
CDSR-1560 submit with securities feature disabled passing
CDSR-1560 add EnterBankAccountDetailsMixin
CDSR-1560 update error message key from enter-bank-details to enter-bank-acount-details in rejected goods scheduled controller
CDSR-1560 Continue when Mandatory fields are filled and bank account is availablei/unavailable passing
CDSR-1560 Display errors when account details are blank passing
=> CDSR-1560 Securities | US1:AC9 /enter-bank-details

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/DisplayDeclaration.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/declaration/SecurityDetails.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/components/summary/SecurityDetailsSummary.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/securities/check_declaration_details.scala.html, conf/messages
After discussing this with BA and Architect, the conclusion is to use only 001, 004, 005 codes. In the highly unlikely event of landing with another one,  we will display `Unavailable`.
=> [CDSR-1859] sharpen the logic for determining payment method

app/assets/javascripts/application.js, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/Head.scala.html, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/Layout.scala.html, conf/application.conf
This PR attemps to remove use of `unsafe-inline` CSP by:
- using CSPNonce for locally hosted scripts
- removal of javascript:history.back() URLs in favour of click event handling
=> [CDSR-1804] remove `unsafe-inline`, use CSPNonce, change back links impl

test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/rejectedgoodssingle/EnterMovementReferenceNumberControllerSpec.scala
Recent content change revealed a test using the wrong messages parameter.
=> Fix test using wrong message

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionBase.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionWithRetrievedData.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/Feature.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchService.scala, conf/application.conf, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/AuthSupport.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthActionSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionWithRetrievedDataSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchServiceSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/TestFeatureSwitchService.scala
This PR adds new feature which can be enabled with adding config property on Github:
features.limited-access: 'true'
When the feature is on then all users are checked against allow list defined as a property:
limited-access-eori-csv-base64: "XYZ"
where XYZ is a Base64 encoded comma-separated list of the allowed EORI numbers
it can be computed using the following command:
echo "GB000000000000001,GB000000000000002" | base64
=> [CDSR-1113] add LimitedAccess feature and configurable allow list of EORI numbers

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterExportMovementReferenceNumberController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/journeys/SecuritiesJourney.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/securities/EnterExportMovementReferenceNumberControllerSpec.scala
This PR fixes a single issue: entering export MRN being the same as current import MRN. There is also a difffent issue: the check for existing import MRN fails for MRNs linked to the Securities, but it works for MRNs linked to NDRC Adjustments. Fixing this problem would require different handling of ACC14 errors in our backend.
=> [CDSR-2041] reject provided export MRN if same as current import MRN

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/cache/FeaturesCache.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/connectors/UploadDocumentsConnector.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedActionWithRetrievedData.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/FeatureSwitchProtectedAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/models/Feature.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchService.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/testonly/controllers/FeatureSwitchController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/views/common/choose_claim_type.scala.html, conf/application.conf, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/cache/FeaturesCacheSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/ControllerSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/FeatureSwitchServiceSpec.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/services/TestFeatureSwitchService.scala
!Attention! This PR is changing how manual feature switching works. 
Before, manually switched feature was observable globally inside the single instance of a service (JVM), making it hard both for acceptance testing and testing manually on multi-instance environments (Dev, QA, Staging). 
After this PR, manually switched feature will be observable inside the current user's session across all service instances.
How to switch feature manually? 
E.g. 
- call /claim-back-import-duty-vat/test-only/feature/overpayments_v2/enable 
- call /claim-back-import-duty-vat/test-only/feature/overpayments_v2/disable
=> [TechDebt] Improve manual feature switches behaviour and scope

app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyBaseController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/JourneyControllerComponents.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/AuthenticatedAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/SessionDataAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/SessionDataActionBase.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/SessionDataActionWithRetrievedData.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/actions/WithAuthAndSessionDataAction.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsmultiple/UploadFilesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/UploadFilesController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentsscheduled/UploadMrnListController.scala, app/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/overpaymentssingle/UploadFilesController.scala, test/uk/gov/hmrc/cdsreimbursementclaimfrontend/controllers/ControllerSpec.scala
This PR fixes regression introduced by the latest libraries upgrade
=> [bugfix] after upgrading the bootstrap library ensure callback is processed with the relevant header carrier converter

conf/messages
I've also removed the old content block for `select-number-of-claims` - I searched for the first part of the key and couldn't find any reference to it and the content seems to largely replicate the overpayments block.
=> CDSR-2482 - Title change for rejected goods
